### PR TITLE
Restuarant page project using webpack and javascript

### PR DESCRIPTION
**Pull request by SamroodAli**
# Project javascript
The project is a restaurant website created using javascript. The elements were inspired by React.
- [x] There are three tabs on the navigation bar
- [x] The links have event listeners attached to them
- [x] The links switch main content
- [x] There is an image
- [x] There is description about the restuarant
- [x] The project has been deployed and added to readme file

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Invalid Review Request

## Please follow Git flow. The development branch should be the default branch and the main branch is only used for production.

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by cyonii — CHANGES_REQUESTED** [review]
### STATUS: CHANGES REQUIRED ♻️✍️

Hello coder, you have done a great job with his project, keep up the energy.

#### TO HIGHLIGHT
- Good PR description 💯
- Simple and clear commit messages 👏
- Neat codebase
- Your project looks professional 😎.

#### TO IMPROVE
- [x] Kindly add a clear instruction in your README on how to open the app in the browser so that anyone can easily get the app started.
- [x] Your issue and LICENSE urls in your README is broken, please fix.

#### NICE TO HAVE
- [ ] It would be nice to add a script to run a development server, e.g,
```javascript
"scripts": {
    "start": "webpack-dev-server --mode development --open" // optional
},
```

Happy coding 💻

> #### <br>Feel free to leave a comment or question if something is not clear.<br> Slack: @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR)<br><br>

**Comment by SamroodAli** [comment]
@cyonii Hi, thanks for reviewing my code. Your time and consideration as well as the compliments are much appreciated. Please clarify what you meant by this requirement.
- [ ]  "Kindly add a clear instruction in your README on how to open the app in the browser so that anyone can easily get the app started".
Is this about adding an explanation on how to use the live link or adding more instructions to the setting up area in readme

**Comment by cyonii** [comment]
> @cyonii Hi, thanks for reviewing my code. Your time and consideration as well as the compliments are much appreciated. Please clarify what you meant by this requirement.
> 
> - [ ]  "Kindly add a clear instruction in your README on how to open the app in the browser so that anyone can easily get the app started".
> 
> Is this about adding an explanation on how to use the live link or adding more instructions to the `Getting started` area in the readme file?

Hello @SamroodAli, for example you could specify the relative path to the file in order to make it useful for non-technical people, e.g, specifying "dist/index.html'

**Comment by SamroodAli** [comment]
@cyonii Thanks for the clarification brother. I have done the following:
- [ ] Added more instructions to the readme on where the index.html file
- [ ] Added a new script to serve the HTML in dist folder in a localhost port
- [ ] Refactored event listeners to single function
- [ ] Refactored redundant function calls for the tabs, menu, home and contact in favour of a single object kept in memory for each tab.
- [ ] Refactored nav links in header to separate module in navLink.js
I will request another cde

**Review by mke2111 — APPROVED** [review]
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The app runs just fine. 👍🏽 
    2. The readme is clear and concise. 👍🏽 

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Comment by SamroodAli** [comment]
Thanks, @mke2111 for reviewing my code and giving me the approval. Happy programming : )

**Pull request merged**
